exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex("bicycle")
    .del()
    .then(function () {
      // Inserts seed entries
      return knex("bicycle").insert([
        {
          bike_name: "56-021",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-022",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-023",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-024",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-025",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-026",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-027",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-028",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-029",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-030",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-031",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-032",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-033",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-034",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-035",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-036",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-037",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-038",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-039",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-040",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-041",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-042",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-043",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-044",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-045",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-046",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-047",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-048",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-049",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-050",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-101",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-102",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-103",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-104",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-105",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-106",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-107",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-108",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-109",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-110",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-111",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-112",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-113",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-114",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-115",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-116",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-117",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-118",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-119",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-120",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "EXC01",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "Have number",
          branch_id: "2",
        },
        {
          bike_name: "EXC02",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "Have number",
          branch_id: "2",
        },
        {
          bike_name: "EXC03",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "Have number",
          branch_id: "2",
        },
        {
          bike_name: "EXC04",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "Have number",
          branch_id: "2",
        },
        {
          bike_name: "EXC05",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "Have number",
          branch_id: "2",
        },
        {
          bike_name: "EXC06",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "Have number",
          branch_id: "2",
        },
        {
          bike_name: "EXC07",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "Have number",
          branch_id: "2",
        },
        {
          bike_name: "EXC08",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "Have number",
          branch_id: "2",
        },
        {
          bike_name: "EXC09",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "Have number",
          branch_id: "2",
        },
        {
          bike_name: "EXC10",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "Have number",
          branch_id: "2",
        },
        {
          bike_name: "EXC11",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "Have number",
          branch_id: "2",
        },
        {
          bike_name: "EXC12",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "Have number",
          branch_id: "2",
        },
        {
          bike_name: "EXC13",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "Have number",
          branch_id: "2",
        },
        {
          bike_name: "EXC14",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "Have number",
          branch_id: "2",
        },
        {
          bike_name: "EXC15",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "Have number",
          branch_id: "2",
        },
        {
          bike_name: "EXC16",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "Have number",
          branch_id: "2",
        },
        {
          bike_name: "EXC17",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "Have number",
          branch_id: "2",
        },
        {
          bike_name: "EXC18",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "Have number",
          branch_id: "2",
        },
        {
          bike_name: "EXC19",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "Have number",
          branch_id: "2",
        },
        {
          bike_name: "EXC20",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "Have number",
          branch_id: "2",
        },
        {
          bike_name: "MTA01",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "MTA02",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "MTA03",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "MTA04",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "MTA05",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "MTA06",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "MTA07",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "MTA08",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "MTA09",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "MTA10",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "MTA11",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "MTA12",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "MTA13",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "MTA14",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "MTA15",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "SOA+D01",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "SOA+D02",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "SOA+D03",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "SOA+D04",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "SOA+D05",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "SOA+D06",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "SOA+D07",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "SOA+D08",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "SOA+D09",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "SOA+D10",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "SOA+D11",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "SOA+D12",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "SOA+D13",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "SOA+D14",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "SOA+D15",
          bike_type_id: "1",
          is_available: "yes",
          detail: "จักรยานแม่บ้าน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "1100",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300005",
          branch_id: "1",
        },
        {
          bike_name: "1101",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300006",
          branch_id: "1",
        },
        {
          bike_name: "1102",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300007",
          branch_id: "1",
        },
        {
          bike_name: "1103",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300008",
          branch_id: "1",
        },
        {
          bike_name: "1104",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300009",
          branch_id: "1",
        },
        {
          bike_name: "1105",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300010",
          branch_id: "1",
        },
        {
          bike_name: "1106",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300011",
          branch_id: "1",
        },
        {
          bike_name: "1107",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300012",
          branch_id: "1",
        },
        {
          bike_name: "1108",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300013",
          branch_id: "1",
        },
        {
          bike_name: "1109",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300014",
          branch_id: "1",
        },
        {
          bike_name: "1110",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300015",
          branch_id: "1",
        },
        {
          bike_name: "1112",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300016",
          branch_id: "1",
        },
        {
          bike_name: "1113",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300017",
          branch_id: "1",
        },
        {
          bike_name: "1114",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300018",
          branch_id: "1",
        },
        {
          bike_name: "1115",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300019",
          branch_id: "1",
        },
        {
          bike_name: "1116",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300020",
          branch_id: "1",
        },
        {
          bike_name: "1117",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300021",
          branch_id: "1",
        },
        {
          bike_name: "1118",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300022",
          branch_id: "1",
        },
        {
          bike_name: "1119",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300023",
          branch_id: "1",
        },
        {
          bike_name: "1120",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300024",
          branch_id: "1",
        },
        {
          bike_name: "1121",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300025",
          branch_id: "1",
        },
        {
          bike_name: "1122",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300026",
          branch_id: "1",
        },
        {
          bike_name: "1123",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300027",
          branch_id: "1",
        },
        {
          bike_name: "1124",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300028",
          branch_id: "1",
        },
        {
          bike_name: "1125",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300029",
          branch_id: "1",
        },
        {
          bike_name: "1126",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300030",
          branch_id: "1",
        },
        {
          bike_name: "1127",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300031",
          branch_id: "1",
        },
        {
          bike_name: "1128",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300032",
          branch_id: "1",
        },
        {
          bike_name: "1129",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300033",
          branch_id: "1",
        },
        {
          bike_name: "1130",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300034",
          branch_id: "1",
        },
        {
          bike_name: "1131",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300035",
          branch_id: "1",
        },
        {
          bike_name: "1132",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300036",
          branch_id: "1",
        },
        {
          bike_name: "1133",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300037",
          branch_id: "1",
        },
        {
          bike_name: "1134",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300038",
          branch_id: "1",
        },
        {
          bike_name: "1135",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300039",
          branch_id: "1",
        },
        {
          bike_name: "1136",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300040",
          branch_id: "1",
        },
        {
          bike_name: "1137",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300041",
          branch_id: "1",
        },
        {
          bike_name: "1138",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300042",
          branch_id: "1",
        },
        {
          bike_name: "1139",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300043",
          branch_id: "1",
        },
        {
          bike_name: "1140",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300044",
          branch_id: "1",
        },
        {
          bike_name: "1141",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300045",
          branch_id: "1",
        },
        {
          bike_name: "1142",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300046",
          branch_id: "1",
        },
        {
          bike_name: "1143",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300047",
          branch_id: "1",
        },
        {
          bike_name: "1144",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300048",
          branch_id: "1",
        },
        {
          bike_name: "1145",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300049",
          branch_id: "1",
        },
        {
          bike_name: "1146",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300050",
          branch_id: "1",
        },
        {
          bike_name: "1147",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300051",
          branch_id: "1",
        },
        {
          bike_name: "1148",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300052",
          branch_id: "1",
        },
        {
          bike_name: "1149",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300053",
          branch_id: "1",
        },
        {
          bike_name: "1150",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300054",
          branch_id: "1",
        },
        {
          bike_name: "1151",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300055",
          branch_id: "1",
        },
        {
          bike_name: "1152",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300056",
          branch_id: "1",
        },
        {
          bike_name: "1153",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300057",
          branch_id: "1",
        },
        {
          bike_name: "1154",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300058",
          branch_id: "1",
        },
        {
          bike_name: "1155",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300059",
          branch_id: "1",
        },
        {
          bike_name: "1156",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300060",
          branch_id: "1",
        },
        {
          bike_name: "1157",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300061",
          branch_id: "1",
        },
        {
          bike_name: "1158",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300062",
          branch_id: "1",
        },
        {
          bike_name: "1159",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300063",
          branch_id: "1",
        },
        {
          bike_name: "1160",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300064",
          branch_id: "1",
        },
        {
          bike_name: "1161",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300065",
          branch_id: "1",
        },
        {
          bike_name: "1162",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300066",
          branch_id: "1",
        },

        {
          bike_name: "1163",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300067",
          branch_id: "1",
        },
        {
          bike_name: "1164",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300068",
          branch_id: "1",
        },

        {
          bike_name: "1165",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300069",
          branch_id: "1",
        },

        {
          bike_name: "1166",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300070",
          branch_id: "1",
        },

        {
          bike_name: "1167",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300071",
          branch_id: "1",
        },
        {
          bike_name: "1168",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300072",
          branch_id: "1",
        },
        {
          bike_name: "1169",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300073",
          branch_id: "1",
        },
        {
          bike_name: "1170",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300074",
          branch_id: "1",
        },
        {
          bike_name: "1171",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300075",
          branch_id: "1",
        },
        {
          bike_name: "1172",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300076",
          branch_id: "1",
        },
        {
          bike_name: "1173",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300077",
          branch_id: "1",
        },
        {
          bike_name: "1174",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300078",
          branch_id: "1",
        },
        {
          bike_name: "1175",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300079",
          branch_id: "1",
        },
        {
          bike_name: "1176",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300080",
          branch_id: "1",
        },
        {
          bike_name: "1177",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300081",
          branch_id: "1",
        },
        {
          bike_name: "1178",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300082",
          branch_id: "1",
        },
        {
          bike_name: "1179",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300083",
          branch_id: "1",
        },
        {
          bike_name: "1180",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300084",
          branch_id: "1",
        },
        {
          bike_name: "1181",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300085",
          branch_id: "1",
        },
        {
          bike_name: "1182",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300086",
          branch_id: "1",
        },
        {
          bike_name: "1183",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300087",
          branch_id: "1",
        },
        {
          bike_name: "1184",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300088",
          branch_id: "1",
        },
        {
          bike_name: "1185",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300089",
          branch_id: "1",
        },
        {
          bike_name: "1186",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300090",
          branch_id: "1",
        },
        {
          bike_name: "1187",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300091",
          branch_id: "1",
        },
        {
          bike_name: "1188",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300092",
          branch_id: "1",
        },
        {
          bike_name: "1189",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300093",
          branch_id: "1",
        },
        {
          bike_name: "1190",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300094",
          branch_id: "1",
        },
        {
          bike_name: "1191",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300095",
          branch_id: "1",
        },
        {
          bike_name: "1192",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300096",
          branch_id: "1",
        },
        {
          bike_name: "1193",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300097",
          branch_id: "1",
        },
        {
          bike_name: "1194",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300098",
          branch_id: "1",
        },
        {
          bike_name: "1195",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "57A0300099",
          branch_id: "1",
        },
        {
          bike_name: "1196",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "1197",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "1198",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "1199",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "1200",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "1201",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "1202",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "1203",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "1204",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "1205",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "1206",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "1207",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "1208",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "1209",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "1210",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "1211",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "1212",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "1213",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "1214",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "1215",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "1216",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "1217",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "1218",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "1219",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "1220",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "1221",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "1222",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "1223",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "1224",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "1225",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "1226",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "",
          branch_id: "3",
        },
        {
          bike_name: "1227",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "",
          branch_id: "3",
        },
        {
          bike_name: "1228",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "",
          branch_id: "3",
        },
        {
          bike_name: "1229",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "",
          branch_id: "3",
        },
        {
          bike_name: "1230",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "",
          branch_id: "3",
        },
        {
          bike_name: "1231",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "",
          branch_id: "3",
        },
        {
          bike_name: "1232",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "",
          branch_id: "3",
        },
        {
          bike_name: "1233",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "",
          branch_id: "3",
        },
        {
          bike_name: "1234",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "",
          branch_id: "3",
        },
        {
          bike_name: "1235",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "",
          branch_id: "3",
        },
        {
          bike_name: "1236",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "",
          branch_id: "3",
        },
        {
          bike_name: "1237",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "",
          branch_id: "3",
        },
        {
          bike_name: "1238",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "",
          branch_id: "3",
        },
        {
          bike_name: "1239",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "",
          branch_id: "3",
        },
        {
          bike_name: "1240",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "",
          branch_id: "3",
        },
        {
          bike_name: "1241",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "",
          branch_id: "3",
        },
        {
          bike_name: "1242",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "",
          branch_id: "3",
        },
        {
          bike_name: "1243",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "",
          branch_id: "3",
        },
        {
          bike_name: "1244",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "",
          branch_id: "3",
        },
        {
          bike_name: "1245",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "",
          branch_id: "3",
        },
        {
          bike_name: "1246",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "",
          branch_id: "3",
        },
        {
          bike_name: "1247",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "",
          branch_id: "3",
        },
        {
          bike_name: "1248",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "",
          branch_id: "3",
        },
        {
          bike_name: "1249",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "",
          branch_id: "3",
        },
        {
          bike_name: "1250",
          bike_type_id: "2",
          is_available: "yes",
          detail: "จักรยานไฮบริด Tiger สีส้ม",
          bike_pic: "",
          bike_eq: "",
          branch_id: "3",
        },
        {
          bike_name: "1054",
          bike_type_id: "3",
          is_available: "yes",
          detail: "จักรยานเสือภูเขา Tiger สีเงิน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "1055",
          bike_type_id: "3",
          is_available: "yes",
          detail: "จักรยานเสือภูเขา Tiger สีเงิน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "1056",
          bike_type_id: "3",
          is_available: "yes",
          detail: "จักรยานเสือภูเขา Tiger สีเงิน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "1057",
          bike_type_id: "3",
          is_available: "yes",
          detail: "จักรยานเสือภูเขา Tiger สีเงิน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "1058",
          bike_type_id: "3",
          is_available: "yes",
          detail: "จักรยานเสือภูเขา Tiger สีเงิน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "1059",
          bike_type_id: "3",
          is_available: "yes",
          detail: "จักรยานเสือภูเขา Tiger สีเงิน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "1060",
          bike_type_id: "3",
          is_available: "yes",
          detail: "จักรยานเสือภูเขา Tiger สีเงิน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "1061",
          bike_type_id: "3",
          is_available: "yes",
          detail: "จักรยานเสือภูเขา Tiger สีเงิน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "1062",
          bike_type_id: "3",
          is_available: "yes",
          detail: "จักรยานเสือภูเขา Tiger สีเงิน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "1063",
          bike_type_id: "3",
          is_available: "yes",
          detail: "จักรยานเสือภูเขา Tiger สีเงิน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "1064",
          bike_type_id: "3",
          is_available: "yes",
          detail: "จักรยานเสือภูเขา Tiger สีเงิน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "1065",
          bike_type_id: "3",
          is_available: "yes",
          detail: "จักรยานเสือภูเขา Tiger สีเงิน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "1066",
          bike_type_id: "3",
          is_available: "yes",
          detail: "จักรยานเสือภูเขา Tiger สีเงิน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "1067",
          bike_type_id: "3",
          is_available: "yes",
          detail: "จักรยานเสือภูเขา Tiger สีเงิน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "1068",
          bike_type_id: "3",
          is_available: "yes",
          detail: "จักรยานเสือภูเขา Tiger สีเงิน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "1069",
          bike_type_id: "3",
          is_available: "yes",
          detail: "จักรยานเสือภูเขา Tiger สีเงิน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "1070",
          bike_type_id: "3",
          is_available: "yes",
          detail: "จักรยานเสือภูเขา Tiger สีเงิน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "1071",
          bike_type_id: "3",
          is_available: "yes",
          detail: "จักรยานเสือภูเขา Tiger สีเงิน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "1072",
          bike_type_id: "3",
          is_available: "yes",
          detail: "จักรยานเสือภูเขา Tiger สีเงิน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "1073",
          bike_type_id: "3",
          is_available: "yes",
          detail: "จักรยานเสือภูเขา Tiger สีเงิน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "1074",
          bike_type_id: "3",
          is_available: "yes",
          detail: "จักรยานเสือภูเขา Tiger สีเงิน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "1075",
          bike_type_id: "3",
          is_available: "yes",
          detail: "จักรยานเสือภูเขา Tiger สีเงิน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "1076",
          bike_type_id: "3",
          is_available: "yes",
          detail: "จักรยานเสือภูเขา Tiger สีเงิน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "1077",
          bike_type_id: "3",
          is_available: "yes",
          detail: "จักรยานเสือภูเขา Tiger สีเงิน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "1078",
          bike_type_id: "3",
          is_available: "yes",
          detail: "จักรยานเสือภูเขา Tiger สีเงิน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-0930",
          bike_type_id: "3",
          is_available: "yes",
          detail: "จักรยานเสือภูเขา LA",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-0931",
          bike_type_id: "3",
          is_available: "yes",
          detail: "จักรยานเสือภูเขา LA",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-0932",
          bike_type_id: "3",
          is_available: "yes",
          detail: "จักรยานเสือภูเขา LA",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-0933",
          bike_type_id: "3",
          is_available: "yes",
          detail: "จักรยานเสือภูเขา LA",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-0934",
          bike_type_id: "3",
          is_available: "yes",
          detail: "จักรยานเสือภูเขา LA",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-0935",
          bike_type_id: "3",
          is_available: "yes",
          detail: "จักรยานเสือภูเขา LA",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-0936",
          bike_type_id: "3",
          is_available: "yes",
          detail: "จักรยานเสือภูเขา LA",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-0937",
          bike_type_id: "3",
          is_available: "yes",
          detail: "จักรยานเสือภูเขา LA",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-0938",
          bike_type_id: "3",
          is_available: "yes",
          detail: "จักรยานเสือภูเขา LA",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "56-0939",
          bike_type_id: "3",
          is_available: "yes",
          detail: "จักรยานเสือภูเขา LA",
          bike_pic: "",
          bike_eq: "",
          branch_id: "1",
        },
        {
          bike_name: "BKT-TG01",
          bike_type_id: "3",
          is_available: "yes",
          detail: "จักรยานเสือภูเขา Tiger สีเงิน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "BKT-TG02",
          bike_type_id: "3",
          is_available: "yes",
          detail: "จักรยานเสือภูเขา Tiger สีเงิน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "BKT-TG03",
          bike_type_id: "3",
          is_available: "yes",
          detail: "จักรยานเสือภูเขา Tiger สีเงิน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "BKT-TG04",
          bike_type_id: "3",
          is_available: "yes",
          detail: "จักรยานเสือภูเขา Tiger สีเงิน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "BKT-TG05",
          bike_type_id: "3",
          is_available: "yes",
          detail: "จักรยานเสือภูเขา Tiger สีเงิน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "BKT-TG06",
          bike_type_id: "3",
          is_available: "yes",
          detail: "จักรยานเสือภูเขา Tiger สีเงิน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "BKT-TG07",
          bike_type_id: "3",
          is_available: "yes",
          detail: "จักรยานเสือภูเขา Tiger สีเงิน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "BKT-TG08",
          bike_type_id: "3",
          is_available: "yes",
          detail: "จักรยานเสือภูเขา Tiger สีเงิน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "BKT-TG09",
          bike_type_id: "3",
          is_available: "yes",
          detail: "จักรยานเสือภูเขา Tiger สีเงิน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "BKT-TG10",
          bike_type_id: "3",
          is_available: "yes",
          detail: "จักรยานเสือภูเขา Tiger สีเงิน",
          bike_pic: "",
          bike_eq: "",
          branch_id: "2",
        },
        {
          bike_name: "1100",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีครีม",
          bike_pic: "",
          bike_eq: "59E0300002",
          branch_id: "1",
        },
        {
          bike_name: "1101",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีครีม",
          bike_pic: "",
          bike_eq: "59E0300003",
          branch_id: "1",
        },
        {
          bike_name: "1102",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีครีม",
          bike_pic: "",
          bike_eq: "59E0300004",
          branch_id: "1",
        },
        {
          bike_name: "1103",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีครีม",
          bike_pic: "",
          bike_eq: "59E0300005",
          branch_id: "1",
        },
        {
          bike_name: "1104",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีครีม",
          bike_pic: "",
          bike_eq: "59E0300006",
          branch_id: "1",
        },
        {
          bike_name: "1105",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีครีม",
          bike_pic: "",
          bike_eq: "59E0300007",
          branch_id: "1",
        },
        {
          bike_name: "1106",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีครีม",
          bike_pic: "",
          bike_eq: "59E0300008",
          branch_id: "1",
        },
        {
          bike_name: "1107",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีครีม",
          bike_pic: "",
          bike_eq: "59E0300009",
          branch_id: "1",
        },
        {
          bike_name: "1108",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีครีม",
          bike_pic: "",
          bike_eq: "59E0300010",
          branch_id: "1",
        },
        {
          bike_name: "1109",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีครีม",
          bike_pic: "",
          bike_eq: "59E0300011",
          branch_id: "1",
        },
        {
          bike_name: "1110",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีครีม",
          bike_pic: "",
          bike_eq: "59E0300012",
          branch_id: "1",
        },
        {
          bike_name: "1111",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีครีม",
          bike_pic: "",
          bike_eq: "59E0300013",
          branch_id: "1",
        },
        {
          bike_name: "1112",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีครีม",
          bike_pic: "",
          bike_eq: "59E0300014",
          branch_id: "1",
        },
        {
          bike_name: "1113",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีครีม",
          bike_pic: "",
          bike_eq: "59E0300015",
          branch_id: "1",
        },
        {
          bike_name: "1114",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีครีม",
          bike_pic: "",
          bike_eq: "59E0300016",
          branch_id: "1",
        },
        {
          bike_name: "1115",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีครีม",
          bike_pic: "",
          bike_eq: "59E0300017",
          branch_id: "1",
        },
        {
          bike_name: "1116",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีครีม",
          bike_pic: "",
          bike_eq: "59E0300018",
          branch_id: "1",
        },
        {
          bike_name: "1117",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีครีม",
          bike_pic: "",
          bike_eq: "59E0300019",
          branch_id: "1",
        },
        {
          bike_name: "1118",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีครีม",
          bike_pic: "",
          bike_eq: "59E0300020",
          branch_id: "1",
        },
        {
          bike_name: "1119",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีครีม",
          bike_pic: "",
          bike_eq: "59E0300021",
          branch_id: "1",
        },
        {
          bike_name: "1120",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีครีม",
          bike_pic: "",
          bike_eq: "59E0300022",
          branch_id: "1",
        },
        {
          bike_name: "1121",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีครีม",
          bike_pic: "",
          bike_eq: "59E0300023",
          branch_id: "1",
        },
        {
          bike_name: "1122",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีครีม",
          bike_pic: "",
          bike_eq: "59E0300024",
          branch_id: "1",
        },
        {
          bike_name: "1123",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีครีม",
          bike_pic: "",
          bike_eq: "59E0300025",
          branch_id: "1",
        },
        {
          bike_name: "1124",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีครีม",
          bike_pic: "",
          bike_eq: "59E0300026",
          branch_id: "1",
        },
        {
          bike_name: "1125",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีครีม",
          bike_pic: "",
          bike_eq: "59E0300027",
          branch_id: "1",
        },
        {
          bike_name: "1126",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีครีม",
          bike_pic: "",
          bike_eq: "59E0300028",
          branch_id: "1",
        },
        {
          bike_name: "1127",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีครีม",
          bike_pic: "",
          bike_eq: "59E0300029",
          branch_id: "1",
        },
        {
          bike_name: "1128",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีครีม",
          bike_pic: "",
          bike_eq: "59E0300030",
          branch_id: "1",
        },
        {
          bike_name: "1129",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีครีม",
          bike_pic: "",
          bike_eq: "59E0300031",
          branch_id: "1",
        },
        {
          bike_name: "1130",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีครีม",
          bike_pic: "",
          bike_eq: "59E0300032",
          branch_id: "1",
        },
        {
          bike_name: "1131",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีครีม",
          bike_pic: "",
          bike_eq: "59E0300033",
          branch_id: "1",
        },
        {
          bike_name: "1132",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีครีม",
          bike_pic: "",
          bike_eq: "59E0300034",
          branch_id: "1",
        },
        {
          bike_name: "1133",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีครีม",
          bike_pic: "",
          bike_eq: "59E0300035",
          branch_id: "1",
        },
        {
          bike_name: "1134",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีครีม",
          bike_pic: "",
          bike_eq: "59E0300036",
          branch_id: "1",
        },
        {
          bike_name: "1135",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีครีม",
          bike_pic: "",
          bike_eq: "59E0300037",
          branch_id: "1",
        },
        {
          bike_name: "1136",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีครีม",
          bike_pic: "",
          bike_eq: "59E0300038",
          branch_id: "1",
        },
        {
          bike_name: "1137",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีครีม",
          bike_pic: "",
          bike_eq: "59E0300039",
          branch_id: "1",
        },
        {
          bike_name: "1138",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีครีม",
          bike_pic: "",
          bike_eq: "59E0300040",
          branch_id: "1",
        },
        {
          bike_name: "1139",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีครีม",
          bike_pic: "",
          bike_eq: "59E0300041",
          branch_id: "1",
        },
        {
          bike_name: "1140",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีขาว",
          bike_pic: "",
          bike_eq: "59E0300042",
          branch_id: "2",
        },
        {
          bike_name: "1141",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีขาว",
          bike_pic: "",
          bike_eq: "59E0300043",
          branch_id: "2",
        },
        {
          bike_name: "1142",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีขาว",
          bike_pic: "",
          bike_eq: "59E0300044",
          branch_id: "2",
        },
        {
          bike_name: "1143",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีขาว",
          bike_pic: "",
          bike_eq: "59E0300045",
          branch_id: "2",
        },
        {
          bike_name: "1144",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีขาว",
          bike_pic: "",
          bike_eq: "59E0300046",
          branch_id: "2",
        },
        {
          bike_name: "1145",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีขาว",
          bike_pic: "",
          bike_eq: "59E0300047",
          branch_id: "2",
        },
        {
          bike_name: "1146",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีขาว",
          bike_pic: "",
          bike_eq: "59E0300048",
          branch_id: "2",
        },
        {
          bike_name: "1147",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีขาว",
          bike_pic: "",
          bike_eq: "59E0300049",
          branch_id: "2",
        },
        {
          bike_name: "1148",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีขาว",
          bike_pic: "",
          bike_eq: "59E0300050",
          branch_id: "2",
        },
        {
          bike_name: "1149",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีขาว",
          bike_pic: "",
          bike_eq: "59E0300051",
          branch_id: "2",
        },
        {
          bike_name: "1150",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีขาว",
          bike_pic: "",
          bike_eq: "59E0300052",
          branch_id: "2",
        },
        {
          bike_name: "1151",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีขาว",
          bike_pic: "",
          bike_eq: "59E0300053",
          branch_id: "2",
        },
        {
          bike_name: "1152",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีขาว",
          bike_pic: "",
          bike_eq: "59E0300054",
          branch_id: "2",
        },
        {
          bike_name: "1153",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีขาว",
          bike_pic: "",
          bike_eq: "59E0300055",
          branch_id: "2",
        },
        {
          bike_name: "1154",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีขาว",
          bike_pic: "",
          bike_eq: "59E0300056",
          branch_id: "2",
        },
        {
          bike_name: "1155",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีขาว",
          bike_pic: "",
          bike_eq: "59E0300057",
          branch_id: "2",
        },
        {
          bike_name: "1156",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีขาว",
          bike_pic: "",
          bike_eq: "59E0300058",
          branch_id: "2",
        },
        {
          bike_name: "1157",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีขาว",
          bike_pic: "",
          bike_eq: "59E0300059",
          branch_id: "2",
        },
        {
          bike_name: "1158",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีขาว",
          bike_pic: "",
          bike_eq: "59E0300060",
          branch_id: "2",
        },
        {
          bike_name: "1159",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีขาว",
          bike_pic: "",
          bike_eq: "59E0300061",
          branch_id: "2",
        },
        {
          bike_name: "1160",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีขาว",
          bike_pic: "",
          bike_eq: "59E0300062",
          branch_id: "2",
        },
        {
          bike_name: "1161",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีขาว",
          bike_pic: "",
          bike_eq: "59E0300063",
          branch_id: "2",
        },
        {
          bike_name: "1162",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีขาว",
          bike_pic: "",
          bike_eq: "59E0300064",
          branch_id: "2",
        },
        {
          bike_name: "1163",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีขาว",
          bike_pic: "",
          bike_eq: "59E0300065",
          branch_id: "2",
        },
        {
          bike_name: "1164",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีขาว",
          bike_pic: "",
          bike_eq: "59E0300066",
          branch_id: "2",
        },
        {
          bike_name: "1165",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีขาว",
          bike_pic: "",
          bike_eq: "59E0300067",
          branch_id: "2",
        },
        {
          bike_name: "1166",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีขาว",
          bike_pic: "",
          bike_eq: "59E0300068",
          branch_id: "2",
        },
        {
          bike_name: "1167",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีขาว",
          bike_pic: "",
          bike_eq: "59E0300069",
          branch_id: "2",
        },
        {
          bike_name: "1168",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีขาว",
          bike_pic: "",
          bike_eq: "59E0300070",
          branch_id: "2",
        },
        {
          bike_name: "1169",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีขาว",
          bike_pic: "",
          bike_eq: "59E0300071",
          branch_id: "2",
        },
        {
          bike_name: "1170",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีขาว",
          bike_pic: "",
          bike_eq: "59E0300072",
          branch_id: "2",
        },
        {
          bike_name: "1171",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีขาว",
          bike_pic: "",
          bike_eq: "59E0300073",
          branch_id: "2",
        },
        {
          bike_name: "1172",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีขาว",
          bike_pic: "",
          bike_eq: "59E0300074",
          branch_id: "2",
        },
        {
          bike_name: "1173",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีขาว",
          bike_pic: "",
          bike_eq: "59E0300075",
          branch_id: "2",
        },
        {
          bike_name: "1174",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีขาว",
          bike_pic: "",
          bike_eq: "59E0300076",
          branch_id: "2",
        },
        {
          bike_name: "1175",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีขาว",
          bike_pic: "",
          bike_eq: "59E0300077",
          branch_id: "2",
        },
        {
          bike_name: "1176",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีขาว",
          bike_pic: "",
          bike_eq: "59E0300078",
          branch_id: "2",
        },
        {
          bike_name: "1177",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีขาว",
          bike_pic: "",
          bike_eq: "59E0300079",
          branch_id: "2",
        },
        {
          bike_name: "1178",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีขาว",
          bike_pic: "",
          bike_eq: "59E0300080",
          branch_id: "2",
        },
        {
          bike_name: "1179",
          bike_type_id: "4",
          is_available: "yes",
          detail: "จักรยานสถานีสีขาว",
          bike_pic: "",
          bike_eq: "59E0300081",
          branch_id: "2",
        },
      ]);
    });
};
